---
- hosts: all
  become: yes
# use --limit to define specific hosts
  gather_facts: yes
  tasks:
# run before bootstrap
  - name: debug
    block:
            - debug:
                    var: hostvars[inventory_hostname]['ansible_default_ipv4']['address']
            - debug:
                    var: hostvars[inventory_hostname]['ansible_dns']['nameservers']

  - name: Register
    block:
            - name: install katello rpm
              shell:
                      cmd: rpm -Uvh {{ katello_url }} 
          
            - name: subscribe to redhat
              redhat_subscription:
                      state: present
                      org_id: "{{ org_id }}"
                      activationkey: "{{ activationkey }}"
              when: ansible_distribution == 'RedHat'

            - name: check repolist added
              shell:
                      cmd: yum repolist
              register: command_output

            - debug:
                    var: command_output.stdout_lines
    ignore_errors: yes
    tags: subs


...
