---
- hosts: all
# use --limit to define specific hosts
  become: yes
  gather_facts: no
  tasks:
# run before bootstrap
  - name: Initial Packages
    block:
            - name: Install Initial {{ basic_packages }} Packages
              yum:
                      name: "{{ item }}"
                      state: latest
                      update_cache: yes
              loop: "{{ basic_packages }}"
    ignore_errors: yes
    tags: packages

  - name: Ceph Packages
    block:
            - name: Install Ceph Packages include {{ ceph_packages }}
              yum:
                      name: "{{ item }}"
                      state: present
              loop: "{{ ceph_packages }}"
    ignore_errors: yes
    tags: ceph

  - name: Time Packages
    block:
            - name: Check tzdata version
              shell:
                      cmd: rpm -qa | grep tzdata
              register: tzdata
            - debug:
                    var: tzdata.stdout_lines
    ignore_errors: yes
    tags: time


...
