---
- hosts: all
# use --limit to define specific hosts
  become: yes
  gather_facts: no
  tasks:
# run before bootstrap
          - name: Install Initial {{ basic_packages }} Packages
            yum:
                    name: "{{ item }}"
                    state: latest
                    update_cache: yes
            loop: "{{ basic_packages }}"
            tags: packages
            ignore_errors: yes

          - name: Install Ceph Packages include {{ ceph_packages }}
            yum:
                    name: "{{ item }}"
                    state: present
            loop: "{{ ceph_packages }}"
            tags: ceph
            ignore_errors: yes

          - name: Check tzdata version
            shell:
                    cmd: rpm -qa | grep tzdata
            register: tzdata
            tags: time
          - debug:
                  var: tzdata.stdout_lines
            tags: time


...
