---
- hosts: all
  # use --limit to define specific hosts
  gather_facts: no
  become: yes
  tasks:
# run before bootstrap only on MON1
# need to modify for each cluster
          - name: Install CephADM Packages
            yum:
                    name:
                            - cephadm
                    state: present
            tags: packages
            ignore_errors: no
           
          - name: Backup Cephadm
            shell:
                    cmd: mv /usr/sbin/cephadm /usr/sbin/cephadm-bkp

          - name: Copy new Cephadm file
            copy:
                    src: /home/ansible/common_config/cephadm
                    dest: /usr/sbin/
                    owner: root
                    group: root
                    mode: '0755'
                    remote_src: no
            tags: packages
#------------------------------------------------------------------
# run After bootstrap only on MON1
# need to modify for each cluster

          - name: Copy osd_spec files
            copy:
                    src: /home/ansible/osd_spec/osd_1.yaml
                    dest: /var/lib/ceph/osd/
                    remote_src: no
            tags: osd

          - name: Copy osd_spec files
            copy:
                    src: /home/ansible/osd_spec/osd_2.yaml
                    dest: /var/lib/ceph/osd/
                    remote_src: no
            tags: osd
          - name: Copy osd_spec files
            copy:
                    src: /home/ansible/osd_spec/osd_3.yaml
                    dest: /var/lib/ceph/osd/
                    remote_src: no
            tags: osd
          - name: Copy osd_spec files
            copy:
                    src: /home/ansible/osd_spec/osd_4.yaml
                    dest: /var/lib/ceph/osd/
                    remote_src: no
            tags: osd
          - name: Copy osd_spec files
            copy:
                    src: /home/ansible/osd_spec/osd_5.yaml
                    dest: /var/lib/ceph/osd/
                    remote_src: no
            tags: osd
          - name: Copy osd_spec files
            copy:
                    src: /home/ansible/osd_spec/osd_6.yaml
                    dest: /var/lib/ceph/osd/
                    remote_src: no
            tags: osd
          - name: Copy osd_spec files
            copy:
                    src: /home/ansible/osd_spec/osd_7.yaml
                    dest: /var/lib/ceph/osd/
                    remote_src: no
            tags: osd
          - name: Copy osd_spec files
            copy:
                    src: /home/ansible/osd_spec/osd_8.yaml
                    dest: /var/lib/ceph/osd/
                    remote_src: no
            tags: osd
          - name: Copy osd_spec script guide
            copy:
                    src: /home/ansible/osd_spec/cat-me.txt
                    dest: /var/lib/ceph/osd/
                    remote_src: no
            tags: osd
#------------------------------------------------------------------
# run After bootstrap only on MANAGERS
# need to modify for each cluster

          - name: set alert enable
            shell:
                    cmd: ceph mgr module enable alerts
            tags: smtp
            ignore_errors: yes
  
          - name: set SMTP host
            shell:
                    cmd: ceph config set mgr mgr/alerts/smtp_host "bulkmail.mci.ir" --force
            tags: smtp
            ignore_errors: yes

          - name: set SMTP destination
            shell:
                    cmd: ceph config set mgr mgr/alerts/smtp_destination storage-team@mci.ir
            tags: smtp
            ignore_errors: yes

            #modify smtp sender for each cluster
          - name: set SMTP sender
            shell:
                    cmd: ceph config set mgr mgr/alerts/smtp_sender {{ smtp_sender }}@noreply.mci.ir
            tags: smtp
            ignore_errors: yes

          - name: disable SSL on SMTP
            shell:
                    cmd: ceph config set mgr mgr/alerts/smtp_ssl false
            tags: smtp
            ignore_errors: yes

          - name: set SMTP port 25
            shell:
                    cmd: ceph config set mgr mgr/alerts/smtp_port 25
            tags: smtp
            ignore_errors: yes

          - name: Send a test alert
            shell:
                    cmd: ceph alerts send
            tags: smtp
            ignore_errors: yes

          - name: display messag
            run_once: yes
            debug:
                    msg:
                            - 'Things need to check: '
                            - '- Plz check your email address (storage-team@mci.ir)'
                            - '- You must recieve an email from {{ smtp_sender }}@noreply.mci.ir' 
                            - '- Email Subject: HEALTH_WARN '
            tags: smtp
...
