---
- hosts: all
  # use --limit to define specific hosts
  gather_facts: no
  become: yes
  tasks:
          - name: set authorized key
            authorized_key:
                    user: root
                    state: present
                    #key will be changed due to each cluster ceph.pub key
                    key: ssh-rsa ...
                    manage_dir: yes
                       

          - name: set authorized key
            authorized_key:
                    user: root
                    state: present
                    #key will be changed due to each cluster mon1 root user public key
                    key: ssh-rsa ...
                    path: /root/.ssh/authorized_keys
                    manage_dir: yes

...
