---
- hosts: all
  # use --limit to define specific hosts
  gather_facts: no
  become: yes
  tasks:
          - name: set 
            authorized_key:
                    user: root
                    state: present
                    key: "{{ ceph_pub }}"
                    path: /root/.ssh/authorized_keys
                    manage_dir: yes

...
