---
- hosts: all
  # use --limit to define specific hosts
  become: yes
  tasks:
  - name: xoroux
    block:
            - name: copy lpar2rrd agent to remote server
              copy:
                    src: /home/ansible/common_config/lpar2rrd-agent.rpm
                    dest: /home/ansible/
                    remote_src: no
                    owner: root
                    group: root
                    mode: '0644'

            - name: go to package directory
              shell:
                      cmd: cd /home/ansible
            - name: Local install package
              shell:
                      cmd: yum localinstall lpar2rrd-agent.rpm -y
            - name: configure package
              shell: 
                      cmd: perl /opt/lpar2rrd-agent/lpar2rrd-agent.pl -d {{ xoroux }}
              register: command_output
            - debug:
                    var: command_output.stdout_lines
    ignore_errors: yes


...
